#
#  Copyright 2022 Il`ya (Marshal) <https://github.com/MarshalX>. All rights reserved.
#
#  Use of this source code is governed by a BSD-style license
#  that can be found in the LICENSE.md file in the root of the project.
#

"""Python bindings to WebRTC, with the API of the browsers."""

from __future__ import annotations

import wrtc as wrtc  # re-exported, the modules import it from the package

from .enums import (
    RTCPeerConnectionState,
    RTCSignalingState,
    RTCIceConnectionState,
    RTCIceGatheringState,
    RTCSdpType,
    MediaStreamTrackState,
    MediaStreamSourceState,
    RTCRtpTransceiverDirection,
    RTCIceComponent,
    RTCIceRole,
    RTCIceTransportState,
    RTCIceGathererState,
    RTCDtlsTransportState,
    RTCSctpTransportState,
    MediaType,
    RTCDataChannelState,
    RTCPriorityType,
    RTCDegradationPreference,
    RTCIceTransportPolicy,
    RTCBundlePolicy,
    RTCRtcpMuxPolicy,
    RTCRtpHeaderEncryptionPolicy,
    RTCIceCandidateType,
    RTCIceProtocol,
    RTCIceTcpCandidateType,
    RTCIceServerTransportProtocol,
    RTCStatsType,
    RTCQualityLimitationReason,
    RTCDtlsRole,
    RTCStatsIceCandidatePairState,
    RTCErrorDetailType,
    BinaryType,
    EndingType,
    VideoPixelFormat,
    VideoColorPrimaries,
    VideoTransferCharacteristics,
    VideoMatrixCoefficients,
    AlphaOption,
    PredefinedColorSpace,
    AudioSampleFormat,
    ReadableStreamReaderMode,
    RTCSdpTypeValue,
    RTCRtpTransceiverDirectionValue,
    MediaTypeValue,
    RTCPriorityTypeValue,
    RTCDegradationPreferenceValue,
    RTCIceTransportPolicyValue,
    RTCBundlePolicyValue,
    RTCRtcpMuxPolicyValue,
    RTCRtpHeaderEncryptionPolicyValue,
    RTCIceServerTransportProtocolValue,
    RTCErrorDetailTypeValue,
    BinaryTypeValue,
    EndingTypeValue,
    VideoPixelFormatValue,
    VideoColorPrimariesValue,
    VideoTransferCharacteristicsValue,
    VideoMatrixCoefficientsValue,
    AlphaOptionValue,
    PredefinedColorSpaceValue,
    AudioSampleFormatValue,
    ReadableStreamReaderModeValue,
    MediaDeviceKind,
    VideoFacingModeEnum,
    VideoResizeModeEnum,
    EchoCancellationModeEnum,
    EncodedVideoChunkType,
    RTCRtpScriptTransformType,
    RTCRtpScriptTransformTypeValue,
    SFrameCipherSuite,
    SFrameCipherSuiteValue,
    SFrameType,
    SFrameTypeValue,
    SFrameTransformErrorEventType,
    SFrameTransformErrorEventTypeValue,
)
from .base import WebRTCObject
from .exceptions import (
    PythonWebRTCExceptionBase,
    PythonWebRTCException,
    SdpParseException,
    RTCException,
    InvalidStateError,
    InvalidAccessError,
    InvalidModificationError,
    OperationError,
    NotSupportedError,
    NetworkError,
    DataCloneError,
    NotFoundError,
    NotAllowedError,
    InvalidSyntaxError,
    InvalidRangeError,
    InvalidCharacterError,
    OverconstrainedError,
    RTCError,
    RTCErrorInit,
)
from .utils.events import EventTarget, HandlerDecorator, UniformEventTarget
from .models.events import (
    Event,
    RTCPeerConnectionIceEvent,
    RTCPeerConnectionIceErrorEvent,
    RTCTrackEvent,
    RTCErrorEvent,
    MessageEvent,
    RTCDataChannelEvent,
    MediaStreamTrackEvent,
    RTCDTMFToneChangeEvent,
    RTCPeerConnectionIceEventInit,
    RTCPeerConnectionIceErrorEventInit,
    RTCTrackEventInit,
    RTCErrorEventInit,
    RTCDataChannelEventInit,
    MediaStreamTrackEventInit,
    RTCDTMFToneChangeEventInit,
    DeviceChangeEvent,
    DeviceChangeEventInit,
    RTCTransformEvent,
    KeyFrameRequestEvent,
    SFrameTransformErrorEvent,
    SFrameTransformErrorEventInit,
)

# the order matters: modules import each other through the package namespace
from .models.rtc_session_description_init import RTCSessionDescriptionInit, RTCLocalSessionDescriptionInit
from .models.rtc_offer_answer_options import RTCOfferAnswerOptions, RTCOfferOptions, RTCAnswerOptions
from .models.rtc_session_description import RTCSessionDescription
from .models.media_track_constraints import (
    ULongRange,
    DoubleRange,
    ConstrainULongRange,
    ConstrainDoubleRange,
    ConstrainBooleanParameters,
    ConstrainDOMStringParameters,
    ConstrainBooleanOrDOMStringParameters,
    MediaTrackSettings,
    MediaTrackSupportedConstraints,
    MediaStreamConstraints,
    MediaTrackCapabilities,
    MediaTrackConstraintSet,
    MediaTrackConstraints,
)
from .models.blob import BlobPropertyBag, Blob
from .models.video_frame import (
    DOMRectReadOnly,
    DOMRectInit,
    PlaneLayout,
    VideoColorSpace,
    VideoColorSpaceInit,
    VideoFrameMetadata,
    VideoFrameBufferInit,
    VideoFrameInit,
    VideoFrameCopyToOptions,
    VideoFrame,
)
from .models.audio_data import AudioDataInit, AudioDataCopyToOptions, AudioData
from .models.rtc_encoded_frame import (
    RTCEncodedFrameMetadata,
    RTCEncodedVideoFrameMetadata,
    RTCEncodedAudioFrameMetadata,
    RTCEncodedVideoFrameOptions,
    RTCEncodedAudioFrameOptions,
    RTCEncodedVideoFrame,
    RTCEncodedAudioFrame,
)
from .models.sframe_transform_options import SFrameTransformOptions, RTCRtpSFrameEncryptorOptions
from .streams import (
    ReadableStream,
    ReadableStreamDefaultReader,
    ReadableStreamDefaultController,
    ReadableStreamReadResult,
    ReadableStreamGetReaderOptions,
    ReadableStreamIteratorOptions,
    ReadableWritablePair,
    StreamPipeOptions,
    QueuingStrategy,
    WritableStream,
    WritableStreamDefaultWriter,
    WritableStreamDefaultController,
    TransformStream,
    TransformStreamDefaultController,
)
from .models.rtp_parameters import (
    RTCRtpParameters,
    RTCRtpCodingParameters,
    RTCEncodingOptions,
    RTCSetParameterOptions,
    RTCRtpCodec,
    RTCRtpCodecParameters,
    RTCRtpHeaderExtensionParameters,
    RTCRtcpParameters,
    RTCRtpEncodingParameters,
    RTCRtpReceiveParameters,
    RTCRtpSendParameters,
    RTCRtpHeaderExtensionCapability,
    RTCRtpCapabilities,
)
from .models.rtc_rtp_transceiver_init import RTCRtpTransceiverInit
from .models.rtc_stats import (
    RTCStats,
    RTCRtpStreamStats,
    RTCCodecStats,
    RTCReceivedRtpStreamStats,
    RTCInboundRtpStreamStats,
    RTCRemoteInboundRtpStreamStats,
    RTCSentRtpStreamStats,
    RTCOutboundRtpStreamStats,
    RTCRemoteOutboundRtpStreamStats,
    RTCMediaSourceStats,
    RTCAudioSourceStats,
    RTCVideoSourceStats,
    RTCAudioPlayoutStats,
    RTCPeerConnectionStats,
    RTCDataChannelStats,
    RTCTransportStats,
    RTCIceCandidateStats,
    RTCIceCandidatePairStats,
    RTCCertificateStats,
    RTCStatsReport,
)
from .models.rtp_source import RTCRtpContributingSource, RTCRtpSynchronizationSource
from .models.rtc_certificate import (
    Algorithm,
    EcKeyGenParams,
    RTCCertificateExpiration,
    RsaHashedKeyGenParams,
    RTCCertificate,
    RTCDtlsFingerprint,
)
from .models.rtc_configuration import (
    RTCConfiguration,
    RTCIceGatherOptions,
    RTCIceServer,
    RTCOAuthCredential,
)
from .models.rtc_ice_candidate import (
    RTCIceCandidate,
    RTCIceCandidateInit,
    RTCLocalIceCandidateInit,
    RTCIceCandidatePair,
    RTCIceParameters,
)

from .interfaces.rtc_peer_connection import RTCPeerConnection
from .interfaces.media_stream_track import MediaStreamTrack
from .interfaces.media_stream import MediaStream
from .interfaces.rtc_rtp_sender import RTCRtpSender
from .interfaces.rtc_rtp_receiver import RTCRtpReceiver
from .interfaces.rtc_rtp_transceiver import RTCRtpTransceiver
from .interfaces.rtc_ice_transport import RTCIceTransport
from .interfaces.rtc_dtls_transport import RTCDtlsTransport
from .interfaces.rtc_sctp_transport import RTCSctpTransport
from .interfaces.rtc_data_channel import RTCDataChannel, RTCDataChannelInit
from .interfaces.media_stream_track_processor import MediaStreamTrackProcessorInit, MediaStreamTrackProcessor
from .interfaces.track_generator import (
    VideoTrackGenerator,
    MediaStreamTrackGeneratorInit,
    MediaStreamTrackGenerator,
)
from .interfaces.rtc_dtmf_sender import RTCDTMFSender
from .interfaces.rtc_rtp_script_transform import WorkerAndParameters, RTCRtpScriptTransformer, RTCRtpScriptTransform
from .interfaces.sframe_transform import (
    RTCRtpSFrameEncryptor,
    RTCRtpSFrameDecryptor,
    SFrameEncryptorStream,
    SFrameDecryptorStream,
)

from .interfaces.media_devices import MediaDeviceInfo, InputDeviceInfo, MediaDevices, media_devices, mediaDevices
from . import openh264


__all__ = [
    'Algorithm',
    'AlphaOption',
    'AlphaOptionValue',
    'AudioData',
    'AudioDataCopyToOptions',
    'AudioDataInit',
    'AudioSampleFormat',
    'AudioSampleFormatValue',
    'BinaryType',
    'BinaryTypeValue',
    'Blob',
    'BlobPropertyBag',
    'ConstrainBooleanOrDOMStringParameters',
    'ConstrainBooleanParameters',
    'ConstrainDOMStringParameters',
    'ConstrainDoubleRange',
    'ConstrainULongRange',
    'DOMRectInit',
    'DOMRectReadOnly',
    'DataCloneError',
    'DeviceChangeEvent',
    'DeviceChangeEventInit',
    'DoubleRange',
    'EcKeyGenParams',
    'EchoCancellationModeEnum',
    'EncodedVideoChunkType',
    'EndingType',
    'EndingTypeValue',
    'Event',
    'EventTarget',
    'HandlerDecorator',
    'InputDeviceInfo',
    'InvalidAccessError',
    'InvalidCharacterError',
    'InvalidModificationError',
    'InvalidRangeError',
    'InvalidStateError',
    'InvalidSyntaxError',
    'KeyFrameRequestEvent',
    'MediaDeviceInfo',
    'MediaDeviceKind',
    'MediaDevices',
    'MediaStream',
    'MediaStreamConstraints',
    'MediaStreamSourceState',
    'MediaStreamTrack',
    'MediaStreamTrackEvent',
    'MediaStreamTrackEventInit',
    'MediaStreamTrackGenerator',
    'MediaStreamTrackGeneratorInit',
    'MediaStreamTrackProcessor',
    'MediaStreamTrackProcessorInit',
    'MediaStreamTrackState',
    'MediaTrackCapabilities',
    'MediaTrackConstraintSet',
    'MediaTrackConstraints',
    'MediaTrackSettings',
    'MediaTrackSupportedConstraints',
    'MediaType',
    'MediaTypeValue',
    'MessageEvent',
    'NetworkError',
    'NotAllowedError',
    'NotFoundError',
    'NotSupportedError',
    'OperationError',
    'OverconstrainedError',
    'PlaneLayout',
    'PredefinedColorSpace',
    'PredefinedColorSpaceValue',
    'PythonWebRTCException',
    'PythonWebRTCExceptionBase',
    'QueuingStrategy',
    'RTCAnswerOptions',
    'RTCAudioPlayoutStats',
    'RTCAudioSourceStats',
    'RTCBundlePolicy',
    'RTCBundlePolicyValue',
    'RTCCertificate',
    'RTCCertificateExpiration',
    'RTCCertificateStats',
    'RTCCodecStats',
    'RTCConfiguration',
    'RTCDTMFSender',
    'RTCDTMFToneChangeEvent',
    'RTCDTMFToneChangeEventInit',
    'RTCDataChannel',
    'RTCDataChannelEvent',
    'RTCDataChannelEventInit',
    'RTCDataChannelInit',
    'RTCDataChannelState',
    'RTCDataChannelStats',
    'RTCDegradationPreference',
    'RTCDegradationPreferenceValue',
    'RTCDtlsFingerprint',
    'RTCDtlsRole',
    'RTCDtlsTransport',
    'RTCDtlsTransportState',
    'RTCEncodedAudioFrame',
    'RTCEncodedAudioFrameMetadata',
    'RTCEncodedAudioFrameOptions',
    'RTCEncodedFrameMetadata',
    'RTCEncodedVideoFrame',
    'RTCEncodedVideoFrameMetadata',
    'RTCEncodedVideoFrameOptions',
    'RTCEncodingOptions',
    'RTCError',
    'RTCErrorDetailType',
    'RTCErrorDetailTypeValue',
    'RTCErrorEvent',
    'RTCErrorEventInit',
    'RTCErrorInit',
    'RTCException',
    'RTCIceCandidate',
    'RTCIceCandidateInit',
    'RTCIceCandidatePair',
    'RTCIceCandidatePairStats',
    'RTCIceCandidateStats',
    'RTCIceCandidateType',
    'RTCIceComponent',
    'RTCIceConnectionState',
    'RTCIceGatherOptions',
    'RTCIceGathererState',
    'RTCIceGatheringState',
    'RTCIceParameters',
    'RTCIceProtocol',
    'RTCIceRole',
    'RTCIceServer',
    'RTCIceServerTransportProtocol',
    'RTCIceServerTransportProtocolValue',
    'RTCIceTcpCandidateType',
    'RTCIceTransport',
    'RTCIceTransportPolicy',
    'RTCIceTransportPolicyValue',
    'RTCIceTransportState',
    'RTCInboundRtpStreamStats',
    'RTCLocalIceCandidateInit',
    'RTCLocalSessionDescriptionInit',
    'RTCMediaSourceStats',
    'RTCOAuthCredential',
    'RTCOfferAnswerOptions',
    'RTCOfferOptions',
    'RTCOutboundRtpStreamStats',
    'RTCPeerConnection',
    'RTCPeerConnectionIceErrorEvent',
    'RTCPeerConnectionIceErrorEventInit',
    'RTCPeerConnectionIceEvent',
    'RTCPeerConnectionIceEventInit',
    'RTCPeerConnectionState',
    'RTCPeerConnectionStats',
    'RTCPriorityType',
    'RTCPriorityTypeValue',
    'RTCQualityLimitationReason',
    'RTCReceivedRtpStreamStats',
    'RTCRemoteInboundRtpStreamStats',
    'RTCRemoteOutboundRtpStreamStats',
    'RTCRtcpMuxPolicy',
    'RTCRtcpMuxPolicyValue',
    'RTCRtcpParameters',
    'RTCRtpCapabilities',
    'RTCRtpCodec',
    'RTCRtpCodecParameters',
    'RTCRtpCodingParameters',
    'RTCRtpContributingSource',
    'RTCRtpEncodingParameters',
    'RTCRtpHeaderEncryptionPolicy',
    'RTCRtpHeaderEncryptionPolicyValue',
    'RTCRtpHeaderExtensionCapability',
    'RTCRtpHeaderExtensionParameters',
    'RTCRtpParameters',
    'RTCRtpReceiveParameters',
    'RTCRtpReceiver',
    'RTCRtpSFrameDecryptor',
    'RTCRtpSFrameEncryptor',
    'RTCRtpSFrameEncryptorOptions',
    'RTCRtpScriptTransform',
    'RTCRtpScriptTransformType',
    'RTCRtpScriptTransformTypeValue',
    'RTCRtpScriptTransformer',
    'RTCRtpSendParameters',
    'RTCRtpSender',
    'RTCRtpStreamStats',
    'RTCRtpSynchronizationSource',
    'RTCRtpTransceiver',
    'RTCRtpTransceiverDirection',
    'RTCRtpTransceiverDirectionValue',
    'RTCRtpTransceiverInit',
    'RTCSctpTransport',
    'RTCSctpTransportState',
    'RTCSdpType',
    'RTCSdpTypeValue',
    'RTCSentRtpStreamStats',
    'RTCSessionDescription',
    'RTCSessionDescriptionInit',
    'RTCSetParameterOptions',
    'RTCSignalingState',
    'RTCStats',
    'RTCStatsIceCandidatePairState',
    'RTCStatsReport',
    'RTCStatsType',
    'RTCTrackEvent',
    'RTCTrackEventInit',
    'RTCTransformEvent',
    'RTCTransportStats',
    'RTCVideoSourceStats',
    'ReadableStream',
    'ReadableStreamDefaultController',
    'ReadableStreamDefaultReader',
    'ReadableStreamGetReaderOptions',
    'ReadableStreamIteratorOptions',
    'ReadableStreamReadResult',
    'ReadableStreamReaderMode',
    'ReadableStreamReaderModeValue',
    'ReadableWritablePair',
    'RsaHashedKeyGenParams',
    'SFrameCipherSuite',
    'SFrameCipherSuiteValue',
    'SFrameDecryptorStream',
    'SFrameEncryptorStream',
    'SFrameTransformErrorEvent',
    'SFrameTransformErrorEventInit',
    'SFrameTransformErrorEventType',
    'SFrameTransformErrorEventTypeValue',
    'SFrameTransformOptions',
    'SFrameType',
    'SFrameTypeValue',
    'SdpParseException',
    'StreamPipeOptions',
    'TransformStream',
    'TransformStreamDefaultController',
    'ULongRange',
    'UniformEventTarget',
    'VideoColorPrimaries',
    'VideoColorPrimariesValue',
    'VideoColorSpace',
    'VideoColorSpaceInit',
    'VideoFacingModeEnum',
    'VideoFrame',
    'VideoFrameBufferInit',
    'VideoFrameCopyToOptions',
    'VideoFrameInit',
    'VideoFrameMetadata',
    'VideoMatrixCoefficients',
    'VideoMatrixCoefficientsValue',
    'VideoPixelFormat',
    'VideoPixelFormatValue',
    'VideoResizeModeEnum',
    'VideoTrackGenerator',
    'VideoTransferCharacteristics',
    'VideoTransferCharacteristicsValue',
    'WebRTCObject',
    'WorkerAndParameters',
    'WritableStream',
    'WritableStreamDefaultController',
    'WritableStreamDefaultWriter',
    'mediaDevices',
    'media_devices',
    'openh264',
]
