[tool.black]
line-length = 120
skip-string-normalization=true
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | .+\.pyi$
)
'''
