// This file includes material copied from WebRTC Extensions, https://w3c.github.io/webrtc-extensions/
// Copyright © 2026 World Wide Web Consortium. https://www.w3.org/copyright/software-license-2023/
// W3C® liability, trademark and permissive document license rules apply. See LICENSE-W3C.md.
// The spec's WebIDL, unchanged, from w3c/webrtc-extensions@9de33afa5311592fc9fdfefa242062022b09849e.

partial dictionary RTCRtpHeaderExtensionCapability {
  required RTCRtpTransceiverDirection direction;
};

partial interface RTCRtpTransceiver {
  sequence<RTCRtpHeaderExtensionCapability> getHeaderExtensionsToNegotiate();
  undefined setHeaderExtensionsToNegotiate(
      sequence<RTCRtpHeaderExtensionCapability> extensions);
  sequence<RTCRtpHeaderExtensionCapability> getNegotiatedHeaderExtensions();
};

partial dictionary RTCRtpEncodingParameters {
    RTCResolutionRestriction scaleResolutionDownTo;
    unsigned long            ptime;
    boolean                  adaptivePtime = false;
};

dictionary RTCResolutionRestriction {
    unsigned long maxWidth;
    unsigned long maxHeight;
};

partial dictionary RTCSetParameterOptions {
  sequence<RTCEncodingOptions> encodingOptions = [];
};

dictionary RTCEncodingOptions {
  boolean keyFrame = false;
};

partial interface RTCIceTransport {
  attribute EventHandler onicecandidatepairadd;
  attribute EventHandler onicecandidatepairremove;
  attribute EventHandler onicecandidatepairnominate;
  Promise<undefined> selectCandidatePair(RTCIceCandidatePair candidatePair);
  Promise<undefined> removeCandidatePair(RTCIceCandidatePair candidatePair);
};

[Exposed=Window]
  interface RTCIceCandidatePairEvent : Event {
    constructor(DOMString type, RTCIceCandidatePairEventInit eventInitDict);
    readonly attribute RTCIceCandidatePair candidatePair;
  };

dictionary RTCIceCandidatePairEventInit : EventInit {
  required RTCIceCandidatePair candidatePair;
};

partial dictionary RTCRtpContributingSource {
  DOMHighResTimeStamp captureTimestamp;
  DOMHighResTimeStamp senderCaptureTimeOffset;
};

  [Exposed=(Window,Worker), Transferable]
  partial interface RTCDataChannel {
};

enum RTCRtpHeaderEncryptionPolicy {
  "disable",
  "negotiate",
  "require"
};

partial dictionary RTCConfiguration {
  RTCRtpHeaderEncryptionPolicy rtpHeaderEncryptionPolicy = "negotiate";
};

partial interface RTCRtpReceiver {
  attribute EventHandler onssrcchange;
  attribute EventHandler oncsrcchange;
};

partial interface RTCRtpReceiver {
  static undefined disableHardwareDecoding();
};

partial interface RTCRtpSender {
  static undefined disableHardwareEncoding();
};

partial dictionary RTCConfiguration {
    boolean alwaysNegotiateDataChannels = false;
};

enum RTCConfigurationTargetLatency {
  "lowest",
  "none"
};
partial dictionary RTCConfiguration {
  RTCConfigurationTargetLatency targetLatency = "lowest";
};

[
  Exposed=Window
] partial interface RTCPeerConnection {
  static DOMString startDiagnosticLogging(optional RTCDiagnosticLoggingOptions options = {});
  static undefined stopDiagnosticLogging();
  static undefined cancelDiagnosticLogging();
};

dictionary RTCDiagnosticLoggingOptions {
  record<DOMString, DOMString> metadata;
};
