from __future__ import annotations
import collections.abc
import typing
import typing_extensions
import webrtc.enums
import webrtc.exceptions
import webrtc.models.media_track_constraints
import webrtc.utils.events
__all__: list[str] = ['ConfigurationInit', 'DataChannelMessage', 'IceCandidateInit', 'IceServerInit', 'MediaStream', 'MediaStreamTrack', 'MediaStreamTrackProcessor', 'PeerConnectionFactory', 'PythonWebRTCException', 'PythonWebRTCExceptionBase', 'RTCCallbackException', 'RTCCertificate', 'RTCDTMFSender', 'RTCDataChannel', 'RTCDtlsTransport', 'RTCEncodedFrame', 'RTCIceTransport', 'RTCPeerConnection', 'RTCRtpReceiver', 'RTCRtpScriptTransform', 'RTCRtpSender', 'RTCRtpTransceiver', 'RTCSctpTransport', 'RTCSessionDescription', 'RTCSessionDescriptionInit', 'RtcpParameters', 'RtpCapabilities', 'RtpCodec', 'RtpCodecCapability', 'RtpCodecParameters', 'RtpEncodingParameters', 'RtpExtension', 'RtpHeaderExtensionCapability', 'RtpParameters', 'RtpTransceiverInit', 'SFrameTransform', 'SdpParseException', 'TrackGenerator', 'VideoFrameBuffer', 'copyAudioSamples', 'disableOpenH264', 'getUserMedia', 'loadOpenH264', 'openH264Enabled', 'ping']
class RTCCallbackException:
    def toPython(self) -> webrtc.exceptions.RTCException:
        ...
class PythonWebRTCExceptionBase(Exception):
    pass
class PythonWebRTCException(PythonWebRTCExceptionBase):
    pass
class SdpParseException(PythonWebRTCExceptionBase):
    pass
class RTCSessionDescriptionInit:
    sdp: str
    @property
    def type(self) -> webrtc.enums.RTCSdpType:
        ...
    @type.setter
    def type(self, value: webrtc.enums.RTCSdpType | webrtc.enums.RTCSdpTypeValue) -> None:
        ...
    def __init__(self, type: webrtc.enums.RTCSdpType | webrtc.enums.RTCSdpTypeValue, sdp: str) -> None:
        ...
class RTCSessionDescription:
    def __init__(self, descriptionInitDict: RTCSessionDescriptionInit) -> None:
        ...
    @property
    def init(self) -> RTCSessionDescriptionInit:
        ...
    @property
    def sdp(self) -> str:
        ...
    @property
    def type(self) -> webrtc.enums.RTCSdpType:
        ...
class IceCandidateInit:
    def kwargs(self) -> _IceCandidateKwargs:
        ...
class RTCCertificate:
    @staticmethod
    def generate(keyType: str, modulusLength: typing.SupportsInt | typing.SupportsIndex, publicExponent: typing.SupportsInt | typing.SupportsIndex, expires: typing.SupportsInt | typing.SupportsIndex | None) -> RTCCertificate:
        ...
    def fingerprints(self) -> list[tuple[str, str]]:
        ...
    @property
    def expires(self) -> int:
        ...
class IceServerInit:
    credential: str | None
    username: str | None
    def __init__(self) -> None:
        ...
    @property
    def urls(self) -> list[str]:
        ...
    @urls.setter
    def urls(self, value: collections.abc.Sequence[str]) -> None:
        ...
class ConfigurationInit:
    alwaysNegotiateDataChannels: bool
    @property
    def bundlePolicy(self) -> webrtc.enums.RTCBundlePolicy:
        ...
    @bundlePolicy.setter
    def bundlePolicy(self, value: webrtc.enums.RTCBundlePolicy | webrtc.enums.RTCBundlePolicyValue) -> None:
        ...
    @property
    def iceTransportPolicy(self) -> webrtc.enums.RTCIceTransportPolicy:
        ...
    @iceTransportPolicy.setter
    def iceTransportPolicy(self, value: webrtc.enums.RTCIceTransportPolicy | webrtc.enums.RTCIceTransportPolicyValue) -> None:
        ...
    @property
    def rtcpMuxPolicy(self) -> webrtc.enums.RTCRtcpMuxPolicy:
        ...
    @rtcpMuxPolicy.setter
    def rtcpMuxPolicy(self, value: webrtc.enums.RTCRtcpMuxPolicy | webrtc.enums.RTCRtcpMuxPolicyValue) -> None:
        ...
    @property
    def rtpHeaderEncryptionPolicy(self) -> webrtc.enums.RTCRtpHeaderEncryptionPolicy:
        ...
    @rtpHeaderEncryptionPolicy.setter
    def rtpHeaderEncryptionPolicy(self, value: webrtc.enums.RTCRtpHeaderEncryptionPolicy | webrtc.enums.RTCRtpHeaderEncryptionPolicyValue) -> None:
        ...
    def __init__(self) -> None:
        ...
    @property
    def certificates(self) -> list[RTCCertificate] | None:
        ...
    @certificates.setter
    def certificates(self, value: collections.abc.Sequence[RTCCertificate] | None) -> None:
        ...
    @property
    def iceCandidatePoolSize(self) -> int:
        ...
    @iceCandidatePoolSize.setter
    def iceCandidatePoolSize(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def iceServers(self) -> list[IceServerInit]:
        ...
    @iceServers.setter
    def iceServers(self, value: collections.abc.Sequence[IceServerInit]) -> None:
        ...
    @property
    def portRange(self) -> tuple[int, int] | None:
        ...
    @portRange.setter
    def portRange(self, value: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex] | None) -> None:
        ...
class RtpCodec:
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @kind.setter
    def kind(self, value: webrtc.enums.MediaType | webrtc.enums.MediaTypeValue) -> None:
        ...
    name: str
    def __init__(self) -> None:
        ...
    @property
    def clockRate(self) -> int | None:
        ...
    @clockRate.setter
    def clockRate(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def mimeType(self) -> str:
        ...
    @property
    def numChannels(self) -> int | None:
        ...
    @numChannels.setter
    def numChannels(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def parameters(self) -> dict[str, str]:
        ...
    @parameters.setter
    def parameters(self, value: collections.abc.Mapping[str, str]) -> None:
        ...
class RtpCodecCapability(RtpCodec):
    def __init__(self) -> None:
        ...
    @property
    def preferredPayloadType(self) -> int | None:
        ...
    @preferredPayloadType.setter
    def preferredPayloadType(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtpCodecParameters(RtpCodec):
    def __init__(self) -> None:
        ...
    @property
    def payloadType(self) -> int:
        ...
    @payloadType.setter
    def payloadType(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class RtpExtension:
    encrypt: bool
    uri: str
    def __init__(self) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class RtpHeaderExtensionCapability:
    @property
    def direction(self) -> webrtc.enums.RTCRtpTransceiverDirection:
        ...
    @direction.setter
    def direction(self, value: webrtc.enums.RTCRtpTransceiverDirection | webrtc.enums.RTCRtpTransceiverDirectionValue) -> None:
        ...
    uri: str
    def __init__(self) -> None:
        ...
    @property
    def preferredId(self) -> int | None:
        ...
    @preferredId.setter
    def preferredId(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtcpParameters:
    cname: str
    reducedSize: bool
    def __init__(self) -> None:
        ...
class RtpEncodingParameters:
    active: bool
    adaptivePtime: bool
    codec: RtpCodec | None
    @property
    def networkPriority(self) -> webrtc.enums.RTCPriorityType:
        ...
    @networkPriority.setter
    def networkPriority(self, value: webrtc.enums.RTCPriorityType | webrtc.enums.RTCPriorityTypeValue) -> None:
        ...
    requestKeyFrame: bool
    rid: str
    scalabilityMode: str | None
    def __init__(self) -> None:
        ...
    @property
    def bitratePriority(self) -> float:
        ...
    @bitratePriority.setter
    def bitratePriority(self, value: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def maxBitrate(self) -> int | None:
        ...
    @maxBitrate.setter
    def maxBitrate(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def maxFramerate(self) -> float | None:
        ...
    @maxFramerate.setter
    def maxFramerate(self, value: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def scaleResolutionDownBy(self) -> float | None:
        ...
    @scaleResolutionDownBy.setter
    def scaleResolutionDownBy(self, value: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def ssrc(self) -> int | None:
        ...
    @ssrc.setter
    def ssrc(self, value: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtpParameters:
    @property
    def degradationPreference(self) -> webrtc.enums.RTCDegradationPreference | None:
        ...
    @degradationPreference.setter
    def degradationPreference(self, value: webrtc.enums.RTCDegradationPreference | webrtc.enums.RTCDegradationPreferenceValue | None) -> None:
        ...
    mid: str
    rtcp: RtcpParameters
    transactionId: str
    def __init__(self) -> None:
        ...
    @property
    def codecs(self) -> list[RtpCodecParameters]:
        ...
    @codecs.setter
    def codecs(self, value: collections.abc.Sequence[RtpCodecParameters]) -> None:
        ...
    @property
    def encodings(self) -> list[RtpEncodingParameters]:
        ...
    @encodings.setter
    def encodings(self, value: collections.abc.Sequence[RtpEncodingParameters]) -> None:
        ...
    @property
    def headerExtensions(self) -> list[RtpExtension]:
        ...
    @headerExtensions.setter
    def headerExtensions(self, value: collections.abc.Sequence[RtpExtension]) -> None:
        ...
class RtpCapabilities:
    def __init__(self) -> None:
        ...
    @property
    def codecs(self) -> list[RtpCodecCapability]:
        ...
    @codecs.setter
    def codecs(self, value: collections.abc.Sequence[RtpCodecCapability]) -> None:
        ...
    @property
    def headerExtensions(self) -> list[RtpHeaderExtensionCapability]:
        ...
    @headerExtensions.setter
    def headerExtensions(self, value: collections.abc.Sequence[RtpHeaderExtensionCapability]) -> None:
        ...
class RtpTransceiverInit:
    @property
    def direction(self) -> webrtc.enums.RTCRtpTransceiverDirection:
        ...
    @direction.setter
    def direction(self, value: webrtc.enums.RTCRtpTransceiverDirection | webrtc.enums.RTCRtpTransceiverDirectionValue) -> None:
        ...
    def __init__(self) -> None:
        ...
    @property
    def sendEncodings(self) -> list[RtpEncodingParameters]:
        ...
    @sendEncodings.setter
    def sendEncodings(self, value: collections.abc.Sequence[RtpEncodingParameters]) -> None:
        ...
    @property
    def streamIds(self) -> list[str]:
        ...
    @streamIds.setter
    def streamIds(self, value: collections.abc.Sequence[str]) -> None:
        ...
class PeerConnectionFactory:
    @staticmethod
    def dispose() -> None:
        ...
    @staticmethod
    def getOrCreateDefault() -> PeerConnectionFactory:
        ...
    def __init__(self) -> None:
        ...
class MediaStreamTrack:
    _constraints: webrtc.models.media_track_constraints.MediaTrackConstraints | None
    _listeners: webrtc.utils.events._Listeners | None
    contentHint: str
    enabled: bool
    def _camera(self) -> tuple[int, int, float] | None:
        ...
    def _reconfigureCamera(self, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, frameRate: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def _settings(self) -> _TrackSettings:
        ...
    def _surfaceEnded(self) -> None:
        ...
    def _surfaceMuted(self, muted: bool) -> None:
        ...
    def clone(self) -> MediaStreamTrack:
        ...
    def stop(self) -> None:
        ...
    @property
    def _nativeId(self) -> str:
        ...
    @property
    def id(self) -> str:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def label(self) -> str:
        ...
    @property
    def muted(self) -> bool:
        ...
    @property
    def readyState(self) -> webrtc.enums.MediaStreamTrackState:
        ...
class MediaStream:
    _listeners: webrtc.utils.events._Listeners | None
    @staticmethod
    def create(tracks: collections.abc.Sequence[MediaStreamTrack]) -> MediaStream:
        ...
    def addTrack(self, track: MediaStreamTrack) -> None:
        ...
    def clone(self) -> MediaStream:
        ...
    def getAudioTracks(self) -> list[MediaStreamTrack]:
        ...
    def getTrackById(self, id: str) -> MediaStreamTrack | None:
        ...
    def getTracks(self) -> list[MediaStreamTrack]:
        ...
    def getVideoTracks(self) -> list[MediaStreamTrack]:
        ...
    def removeTrack(self, track: MediaStreamTrack) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def id(self) -> str:
        ...
class RTCIceTransport:
    _listeners: webrtc.utils.events._Listeners | None
    def __init__(self) -> None:
        ...
    def _surfaceCandidate(self) -> None:
        ...
    def _surfaceGatheringState(self, state: webrtc.enums.RTCIceGathererState) -> None:
        ...
    def _surfaceState(self, state: webrtc.enums.RTCIceTransportState) -> None:
        ...
    def addRemoteCandidate(self, candidate: str, sdpMid: str, sdpMLineIndex: typing.SupportsInt | typing.SupportsIndex, usernameFragment: str | None) -> None:
        ...
    def gather(self, policy: webrtc.enums.RTCIceTransportPolicy | webrtc.enums.RTCIceTransportPolicyValue, iceServers: collections.abc.Sequence[IceServerInit]) -> None:
        ...
    def getLocalCandidates(self) -> list[IceCandidateInit]:
        ...
    def getLocalParameters(self) -> tuple[str, str] | None:
        ...
    def getRemoteCandidates(self) -> list[IceCandidateInit]:
        ...
    def getRemoteParameters(self) -> tuple[str, str] | None:
        ...
    def getSelectedCandidatePair(self) -> tuple[IceCandidateInit, IceCandidateInit, bool] | None:
        ...
    def start(self, usernameFragment: str, password: str, role: webrtc.enums.RTCIceRole) -> None:
        ...
    def stop(self) -> None:
        ...
    @property
    def _standalone(self) -> bool:
        ...
    @property
    def component(self) -> webrtc.enums.RTCIceComponent:
        ...
    @property
    def gatheringState(self) -> webrtc.enums.RTCIceGathererState:
        ...
    @property
    def role(self) -> webrtc.enums.RTCIceRole:
        ...
    @property
    def state(self) -> webrtc.enums.RTCIceTransportState:
        ...
class RTCDtlsTransport:
    _listeners: webrtc.utils.events._Listeners | None
    def _surfaceState(self, state: webrtc.enums.RTCDtlsTransportState) -> None:
        ...
    def getRemoteCertificates(self) -> list[bytes]:
        ...
    @property
    def iceTransport(self) -> RTCIceTransport:
        ...
    @property
    def state(self) -> webrtc.enums.RTCDtlsTransportState:
        ...
class RTCSctpTransport:
    _listeners: webrtc.utils.events._Listeners | None
    def _surfaceState(self, state: webrtc.enums.RTCSctpTransportState) -> None:
        ...
    @property
    def maxChannels(self) -> int | None:
        ...
    @property
    def maxMessageSize(self) -> float | None:
        ...
    @property
    def state(self) -> webrtc.enums.RTCSctpTransportState:
        ...
    @property
    def transport(self) -> RTCDtlsTransport:
        ...
class RTCDTMFSender:
    _listeners: webrtc.utils.events._Listeners | None
    def _surfaceBuffer(self, buffer: str, insertion: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def insertDTMF(self, tones: str, duration: typing.SupportsInt | typing.SupportsIndex, interToneGap: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def canInsertDTMF(self) -> bool:
        ...
    @property
    def toneBuffer(self) -> str:
        ...
class RTCRtpSender:
    @property
    def transform(self) -> _RtpTransform | None:
        ...
    @transform.setter
    def transform(self, value: _RtpTransform | None) -> None:
        ...
    @staticmethod
    def getCapabilities(kind: str) -> RtpCapabilities | None:
        ...
    def _expireParameters(self, transactionId: str | None = None) -> None:
        ...
    def _lastParameters(self) -> RtpParameters | None:
        ...
    def _transceiverStopped(self) -> bool:
        ...
    def getParameters(self) -> RtpParameters:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    def getStreamIds(self) -> list[str]:
        ...
    def replaceTrack(self, track: MediaStreamTrack | None) -> bool:
        ...
    def setParameters(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], parameters: RtpParameters) -> None:
        ...
    def setStreams(self, streamIds: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def dtmf(self) -> RTCDTMFSender:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def track(self) -> MediaStreamTrack | None:
        ...
    @property
    def transport(self) -> RTCDtlsTransport | None:
        ...
class RTCRtpReceiver:
    @property
    def transform(self) -> _RtpTransform | None:
        ...
    @transform.setter
    def transform(self, value: _RtpTransform | None) -> None:
        ...
    @staticmethod
    def getCapabilities(kind: str) -> RtpCapabilities | None:
        ...
    def _getSources(self) -> list[tuple[bool, int, float, int, int | None]]:
        ...
    def getParameters(self) -> RtpParameters:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    @property
    def jitterBufferTarget(self) -> float | None:
        ...
    @jitterBufferTarget.setter
    def jitterBufferTarget(self, value: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def track(self) -> MediaStreamTrack:
        ...
    @property
    def transport(self) -> RTCDtlsTransport | None:
        ...
class RTCRtpTransceiver:
    @property
    def direction(self) -> webrtc.enums.RTCRtpTransceiverDirection:
        ...
    @direction.setter
    def direction(self, value: webrtc.enums.RTCRtpTransceiverDirection | webrtc.enums.RTCRtpTransceiverDirectionValue) -> None:
        ...
    def getCodecPreferences(self) -> list[RtpCodecCapability]:
        ...
    def getHeaderExtensionsToNegotiate(self) -> list[RtpHeaderExtensionCapability]:
        ...
    def getNegotiatedHeaderExtensions(self) -> list[RtpHeaderExtensionCapability]:
        ...
    def setCodecPreferences(self, codecs: collections.abc.Sequence[RtpCodecCapability]) -> None:
        ...
    def setHeaderExtensionsToNegotiate(self, extensions: collections.abc.Sequence[RtpHeaderExtensionCapability]) -> None:
        ...
    def stop(self) -> None:
        ...
    @property
    def currentDirection(self) -> webrtc.enums.RTCRtpTransceiverDirection | None:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def mid(self) -> str | None:
        ...
    @property
    def receiver(self) -> RTCRtpReceiver:
        ...
    @property
    def sender(self) -> RTCRtpSender:
        ...
    @property
    def stopped(self) -> bool:
        ...
    @property
    def stopping(self) -> bool:
        ...
class DataChannelMessage:
    @property
    def data(self) -> str | bytes:
        ...
class RTCDataChannel:
    _listeners: webrtc.utils.events._Listeners | None
    binaryType: str
    def _decreaseBufferedAmount(self, sent: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def _release(self) -> None:
        ...
    def _surfaceState(self, state: webrtc.enums.RTCDataChannelState) -> None:
        ...
    def close(self) -> None:
        ...
    def send(self, data: str | bytes, binary: bool) -> None:
        ...
    @property
    def bufferedAmount(self) -> int:
        ...
    @property
    def bufferedAmountLowThreshold(self) -> int:
        ...
    @bufferedAmountLowThreshold.setter
    def bufferedAmountLowThreshold(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def id(self) -> int | None:
        ...
    @property
    def label(self) -> str:
        ...
    @property
    def maxPacketLifeTime(self) -> int | None:
        ...
    @property
    def maxRetransmits(self) -> int | None:
        ...
    @property
    def negotiated(self) -> bool:
        ...
    @property
    def ordered(self) -> bool:
        ...
    @property
    def priority(self) -> webrtc.enums.RTCPriorityType:
        ...
    @property
    def protocol(self) -> str:
        ...
    @property
    def readyState(self) -> webrtc.enums.RTCDataChannelState:
        ...
class RTCPeerConnection:
    _listeners: webrtc.utils.events._Listeners | None
    @staticmethod
    def _connectionOf(sender: RTCRtpSender) -> RTCPeerConnection | None:
        ...
    def __init__(self, configuration: ConfigurationInit | None) -> None:
        ...
    def _applyDescriptions(self, snapshot: typing.SupportsInt | typing.SupportsIndex | None = None) -> None:
        ...
    def _refreshDescriptions(self) -> None:
        ...
    def _shouldFireNegotiationNeededEvent(self, eventId: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def _surfaceConnectionState(self, state: webrtc.enums.RTCPeerConnectionState) -> None:
        ...
    def _surfaceIceConnectionState(self, state: webrtc.enums.RTCIceConnectionState) -> None:
        ...
    def _surfaceIceGatheringState(self, state: webrtc.enums.RTCIceGatheringState) -> None:
        ...
    def _surfaceSignalingState(self, state: webrtc.enums.RTCSignalingState) -> None:
        ...
    def addIceCandidate(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], candidate: str, sdpMid: str | None, sdpMLineIndex: typing.SupportsInt | typing.SupportsIndex | None, usernameFragment: str | None) -> None:
        ...
    @typing.overload
    def addTrack(self, track: MediaStreamTrack, stream: MediaStream | None) -> RTCRtpSender:
        ...
    @typing.overload
    def addTrack(self, track: MediaStreamTrack, streams: collections.abc.Sequence[MediaStream]) -> RTCRtpSender:
        ...
    @typing.overload
    def addTransceiver(self, kind: webrtc.enums.MediaType | webrtc.enums.MediaTypeValue, init: RtpTransceiverInit | None) -> RTCRtpTransceiver:
        ...
    @typing.overload
    def addTransceiver(self, track: MediaStreamTrack, init: RtpTransceiverInit | None) -> RTCRtpTransceiver:
        ...
    def close(self) -> None:
        ...
    def createAnswer(self, onSuccess: collections.abc.Callable[[RTCSessionDescription], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    def createDataChannel(self, label: str, ordered: bool, maxPacketLifeTime: typing.SupportsInt | typing.SupportsIndex | None, maxRetransmits: typing.SupportsInt | typing.SupportsIndex | None, protocol: str, negotiated: bool, id: typing.SupportsInt | typing.SupportsIndex | None, priority: webrtc.enums.RTCPriorityType | webrtc.enums.RTCPriorityTypeValue) -> RTCDataChannel:
        ...
    def createOffer(self, onSuccess: collections.abc.Callable[[RTCSessionDescription], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], iceRestart: bool) -> None:
        ...
    def getConfiguration(self) -> ConfigurationInit:
        ...
    def getReceivers(self) -> list[RTCRtpReceiver]:
        ...
    def getSenders(self) -> list[RTCRtpSender]:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    def getTransceivers(self) -> list[RTCRtpTransceiver]:
        ...
    def removeTrack(self, sender: RTCRtpSender) -> None:
        ...
    def restartIce(self) -> None:
        ...
    def setConfiguration(self, configuration: ConfigurationInit) -> None:
        ...
    def setLocalDescription(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], description: RTCSessionDescriptionInit | None) -> None:
        ...
    def setRemoteDescription(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], description: RTCSessionDescriptionInit) -> None:
        ...
    @property
    def canTrickleIceCandidates(self) -> bool | None:
        ...
    @property
    def connectionState(self) -> webrtc.enums.RTCPeerConnectionState:
        ...
    @property
    def currentLocalDescription(self) -> RTCSessionDescription:
        ...
    @property
    def currentRemoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def iceConnectionState(self) -> webrtc.enums.RTCIceConnectionState:
        ...
    @property
    def iceGatheringState(self) -> webrtc.enums.RTCIceGatheringState:
        ...
    @property
    def localDescription(self) -> RTCSessionDescription:
        ...
    @property
    def pendingLocalDescription(self) -> RTCSessionDescription:
        ...
    @property
    def pendingRemoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def remoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def sctp(self) -> RTCSctpTransport | None:
        ...
    @property
    def signalingState(self) -> webrtc.enums.RTCSignalingState:
        ...
class VideoFrameBuffer:
    @staticmethod
    def fromData(format: str, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, data: typing_extensions.Buffer, layout: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]) -> VideoFrameBuffer:
        ...
    def convertTo(self, destination: typing_extensions.Buffer, format: str, x: typing.SupportsInt | typing.SupportsIndex, y: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, offset: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex, matrix: str, fullRange: bool) -> None:
        ...
    def copyPlanes(self, destination: typing_extensions.Buffer, planes: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
    def withoutAlpha(self) -> VideoFrameBuffer:
        ...
    @property
    def format(self) -> str:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class MediaStreamTrackProcessor:
    _listeners: webrtc.utils.events._Listeners | None
    def __init__(self, track: MediaStreamTrack, maxBufferSize: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def _ackWakeup(self) -> None:
        ...
    def cancel(self) -> None:
        ...
    def read(self) -> tuple[VideoFrameBuffer, int, int, int] | tuple[bytes, int, int, int, int, int] | None:
        ...
    @property
    def discardedFrames(self) -> int:
        ...
    @property
    def ended(self) -> bool:
        ...
    @property
    def totalFrames(self) -> int:
        ...
class _RtpTransform:
    pass
class RTCEncodedFrame:
    def getData(self) -> bytes:
        ...
    def getMetadata(self) -> dict[str, object]:
        ...
    @property
    def video(self) -> bool:
        ...
class RTCRtpScriptTransform(_RtpTransform):
    _listeners: webrtc.utils.events._Listeners | None
    def __init__(self) -> None:
        ...
    def _ackWakeup(self) -> None:
        ...
    def generateKeyFrame(self, rid: str | None) -> int:
        ...
    def read(self) -> RTCEncodedFrame | None:
        ...
    def sendKeyFrameRequest(self) -> bool:
        ...
    def write(self, frame: RTCEncodedFrame, data: typing_extensions.Buffer | None) -> bool:
        ...
    @property
    def sourceId(self) -> int:
        ...
    @property
    def sourceKind(self) -> tuple[bool, bool] | None:
        ...
    @property
    def state(self) -> int:
        ...
class SFrameTransform(_RtpTransform):
    _listeners: webrtc.utils.events._Listeners | None
    def __init__(self, cipherSuite: typing.SupportsInt | typing.SupportsIndex, encrypting: bool) -> None:
        ...
    def addDecryptionKey(self, key: typing_extensions.Buffer, keyId: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def decrypt(self, data: typing_extensions.Buffer) -> tuple[bytes | None, int, int | None]:
        ...
    def encrypt(self, data: typing_extensions.Buffer) -> bytes | None:
        ...
    def removeDecryptionKey(self, keyId: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def setEncryptionKey(self, key: typing_extensions.Buffer, keyId: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @property
    def encrypting(self) -> bool:
        ...
class TrackGenerator:
    muted: bool
    def __init__(self, kind: str) -> None:
        ...
    def close(self) -> None:
        ...
    def writeAudio(self, samples: bytes, sampleRate: typing.SupportsInt | typing.SupportsIndex, channels: typing.SupportsInt | typing.SupportsIndex, frames: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def writeVideo(self, buffer: VideoFrameBuffer, timestampUs: typing.SupportsInt | typing.SupportsIndex, rotation: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def kind(self) -> str:
        ...
    @property
    def live(self) -> bool:
        ...
    @property
    def track(self) -> MediaStreamTrack:
        ...
def _alive() -> dict[str, int]:
    ...
def _alive_factories() -> int:
    ...
def _sframeDecrypt(cipherSuite: typing.SupportsInt | typing.SupportsIndex, baseKey: typing_extensions.Buffer, metadata: typing_extensions.Buffer, ciphertext: typing_extensions.Buffer) -> bytes | None:
    ...
def _sframeDerive(cipherSuite: typing.SupportsInt | typing.SupportsIndex, baseKey: typing_extensions.Buffer, keyId: typing.SupportsInt | typing.SupportsIndex) -> tuple[bytes, bytes]:
    ...
def _sframeEncrypt(cipherSuite: typing.SupportsInt | typing.SupportsIndex, baseKey: typing_extensions.Buffer, keyId: typing.SupportsInt | typing.SupportsIndex, counter: typing.SupportsInt | typing.SupportsIndex, metadata: typing_extensions.Buffer, plaintext: typing_extensions.Buffer) -> bytes:
    ...
def _sframeHeader(keyId: typing.SupportsInt | typing.SupportsIndex, counter: typing.SupportsInt | typing.SupportsIndex) -> bytes:
    ...
def _sframeParseHeader(data: typing_extensions.Buffer) -> tuple[int, int, int] | None:
    ...
def copyAudioSamples(source: typing_extensions.Buffer, sourceFormat: str, channels: typing.SupportsInt | typing.SupportsIndex, frames: typing.SupportsInt | typing.SupportsIndex, destination: typing_extensions.Buffer, destinationFormat: str, planeIndex: typing.SupportsInt | typing.SupportsIndex, frameOffset: typing.SupportsInt | typing.SupportsIndex, frameCount: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def disableOpenH264() -> None:
    ...
def getUserMedia(audio: bool, video: bool, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, frameRate: typing.SupportsFloat | typing.SupportsIndex) -> MediaStream:
    ...
def loadOpenH264(path: str) -> str:
    ...
def openH264Enabled() -> bool:
    ...
def ping() -> None:
    ...
_sanitized: bool = False
class _IceCandidateKwargs(typing_extensions.TypedDict, closed=True):
    candidate: str
    sdp_mid: str
    sdp_m_line_index: int
    username_fragment: str | None
    url: str | None
    relay_protocol: typing.Literal['udp', 'tcp', 'tls'] | None
class _TrackSettings(typing.TypedDict, total=False):
    width: int
    height: int
    frame_rate: float
    device: typing.Literal['camera', 'microphone']
    sample_rate: int
    channel_count: int
    sample_size: int
