from __future__ import annotations
import collections.abc
import typing
import webrtc.enums
__all__: list[str] = ['ConfigurationInit', 'DataChannelMessage', 'IceCandidateInit', 'IceServerInit', 'MediaStream', 'MediaStreamTrack', 'MediaStreamTrackProcessor', 'PeerConnectionFactory', 'PythonWebRTCException', 'PythonWebRTCExceptionBase', 'RTCCallbackException', 'RTCCertificate', 'RTCDTMFSender', 'RTCDataChannel', 'RTCDtlsTransport', 'RTCIceTransport', 'RTCPeerConnection', 'RTCRtpReceiver', 'RTCRtpSender', 'RTCRtpTransceiver', 'RTCSctpTransport', 'RTCSessionDescription', 'RTCSessionDescriptionInit', 'RtcpParameters', 'RtpCapabilities', 'RtpCodec', 'RtpCodecCapability', 'RtpCodecParameters', 'RtpEncodingParameters', 'RtpExtension', 'RtpHeaderExtensionCapability', 'RtpParameters', 'RtpTransceiverInit', 'SdpParseException', 'TrackGenerator', 'VideoFrameBuffer', 'copyAudioSamples', 'getUserMedia', 'ping']
class RTCCallbackException:
    def toPython(self) -> typing.Any:
        ...
class PythonWebRTCExceptionBase(Exception):
    pass
class PythonWebRTCException(PythonWebRTCExceptionBase):
    pass
class SdpParseException(PythonWebRTCExceptionBase):
    pass
class RTCSessionDescriptionInit:
    sdp: str
    type: webrtc.enums.RTCSdpType
    def __init__(self, arg0: webrtc.enums.RTCSdpType, arg1: str) -> None:
        ...
class RTCSessionDescription:
    def __init__(self, arg0: RTCSessionDescriptionInit) -> None:
        ...
    @property
    def init(self) -> RTCSessionDescriptionInit:
        ...
    @property
    def sdp(self) -> str:
        ...
    @property
    def type(self) -> webrtc.enums.RTCSdpType:
        ...
class IceCandidateInit:
    def kwargs(self) -> dict:
        ...
class RTCCertificate:
    @staticmethod
    def generate(keyType: str, modulusLength: typing.SupportsInt | typing.SupportsIndex, publicExponent: typing.SupportsInt | typing.SupportsIndex, expires: typing.SupportsInt | typing.SupportsIndex | None) -> RTCCertificate:
        ...
    def fingerprints(self) -> list[tuple[str, str]]:
        ...
    @property
    def expires(self) -> int:
        ...
class IceServerInit:
    credential: str | None
    username: str | None
    def __init__(self) -> None:
        ...
    @property
    def urls(self) -> list[str]:
        ...
    @urls.setter
    def urls(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
class ConfigurationInit:
    alwaysNegotiateDataChannels: bool
    bundlePolicy: webrtc.enums.RTCBundlePolicy
    iceTransportPolicy: webrtc.enums.RTCIceTransportPolicy
    rtcpMuxPolicy: webrtc.enums.RTCRtcpMuxPolicy
    rtpHeaderEncryptionPolicy: webrtc.enums.RTCRtpHeaderEncryptionPolicy
    def __init__(self) -> None:
        ...
    @property
    def certificates(self) -> list[RTCCertificate] | None:
        ...
    @certificates.setter
    def certificates(self, arg0: collections.abc.Sequence[RTCCertificate] | None) -> None:
        ...
    @property
    def iceCandidatePoolSize(self) -> int:
        ...
    @iceCandidatePoolSize.setter
    def iceCandidatePoolSize(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def iceServers(self) -> list[IceServerInit]:
        ...
    @iceServers.setter
    def iceServers(self, arg0: collections.abc.Sequence[IceServerInit]) -> None:
        ...
    @property
    def portRange(self) -> tuple[int, int] | None:
        ...
    @portRange.setter
    def portRange(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex] | None) -> None:
        ...
class RtpCodec:
    kind: webrtc.enums.MediaType
    name: str
    def __init__(self) -> None:
        ...
    @property
    def clockRate(self) -> int | None:
        ...
    @clockRate.setter
    def clockRate(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def mimeType(self) -> str:
        ...
    @property
    def numChannels(self) -> int | None:
        ...
    @numChannels.setter
    def numChannels(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def parameters(self) -> dict[str, str]:
        ...
    @parameters.setter
    def parameters(self, arg1: collections.abc.Mapping[str, str]) -> None:
        ...
class RtpCodecCapability(RtpCodec):
    def __init__(self) -> None:
        ...
    @property
    def preferredPayloadType(self) -> int | None:
        ...
    @preferredPayloadType.setter
    def preferredPayloadType(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtpCodecParameters(RtpCodec):
    def __init__(self) -> None:
        ...
    @property
    def payloadType(self) -> int:
        ...
    @payloadType.setter
    def payloadType(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class RtpExtension:
    encrypt: bool
    uri: str
    def __init__(self) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class RtpHeaderExtensionCapability:
    direction: webrtc.enums.TransceiverDirection
    uri: str
    def __init__(self) -> None:
        ...
    @property
    def preferredId(self) -> int | None:
        ...
    @preferredId.setter
    def preferredId(self, arg1: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtcpParameters:
    cname: str
    reducedSize: bool
    def __init__(self) -> None:
        ...
class RtpEncodingParameters:
    active: bool
    adaptivePtime: bool
    codec: RtpCodec | None
    networkPriority: webrtc.enums.RTCPriorityType
    requestKeyFrame: bool
    rid: str
    scalabilityMode: str | None
    def __init__(self) -> None:
        ...
    @property
    def bitratePriority(self) -> float:
        ...
    @bitratePriority.setter
    def bitratePriority(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def maxBitrate(self) -> int | None:
        ...
    @maxBitrate.setter
    def maxBitrate(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
    @property
    def maxFramerate(self) -> float | None:
        ...
    @maxFramerate.setter
    def maxFramerate(self, arg0: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def scaleResolutionDownBy(self) -> float | None:
        ...
    @scaleResolutionDownBy.setter
    def scaleResolutionDownBy(self, arg0: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def ssrc(self) -> int | None:
        ...
    @ssrc.setter
    def ssrc(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class RtpParameters:
    degradationPreference: webrtc.enums.RTCDegradationPreference | None
    mid: str
    rtcp: RtcpParameters
    transactionId: str
    def __init__(self) -> None:
        ...
    @property
    def codecs(self) -> list[RtpCodecParameters]:
        ...
    @codecs.setter
    def codecs(self, arg0: collections.abc.Sequence[RtpCodecParameters]) -> None:
        ...
    @property
    def encodings(self) -> list[RtpEncodingParameters]:
        ...
    @encodings.setter
    def encodings(self, arg0: collections.abc.Sequence[RtpEncodingParameters]) -> None:
        ...
    @property
    def headerExtensions(self) -> list[RtpExtension]:
        ...
    @headerExtensions.setter
    def headerExtensions(self, arg0: collections.abc.Sequence[RtpExtension]) -> None:
        ...
class RtpCapabilities:
    def __init__(self) -> None:
        ...
    @property
    def codecs(self) -> list[RtpCodecCapability]:
        ...
    @codecs.setter
    def codecs(self, arg0: collections.abc.Sequence[RtpCodecCapability]) -> None:
        ...
    @property
    def headerExtensions(self) -> list[RtpHeaderExtensionCapability]:
        ...
    @headerExtensions.setter
    def headerExtensions(self, arg0: collections.abc.Sequence[RtpHeaderExtensionCapability]) -> None:
        ...
class RtpTransceiverInit:
    direction: webrtc.enums.TransceiverDirection
    def __init__(self) -> None:
        ...
    @property
    def sendEncodings(self) -> list[RtpEncodingParameters]:
        ...
    @sendEncodings.setter
    def sendEncodings(self, arg0: collections.abc.Sequence[RtpEncodingParameters]) -> None:
        ...
    @property
    def streamIds(self) -> list[str]:
        ...
    @streamIds.setter
    def streamIds(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
class PeerConnectionFactory:
    @staticmethod
    def dispose() -> None:
        ...
    @staticmethod
    def getOrCreateDefault() -> PeerConnectionFactory:
        ...
    def __init__(self) -> None:
        ...
class MediaStreamTrack:
    _constraints: typing.Any
    _listeners: typing.Any
    contentHint: str
    enabled: bool
    def _camera(self) -> tuple[int, int, float] | None:
        ...
    def _reconfigureCamera(self, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, frameRate: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def _settings(self) -> dict:
        ...
    def _surfaceEnded(self) -> None:
        ...
    def _surfaceMuted(self, muted: bool) -> None:
        ...
    def clone(self) -> MediaStreamTrack:
        ...
    def stop(self) -> None:
        ...
    @property
    def _nativeId(self) -> str:
        ...
    @property
    def id(self) -> str:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def label(self) -> str:
        ...
    @property
    def muted(self) -> bool:
        ...
    @property
    def readyState(self) -> webrtc.enums.MediaStreamTrackState:
        ...
class MediaStream:
    _listeners: typing.Any
    @staticmethod
    def create(tracks: collections.abc.Sequence[MediaStreamTrack]) -> MediaStream:
        ...
    def addTrack(self, track: MediaStreamTrack) -> None:
        ...
    def clone(self) -> MediaStream:
        ...
    def getAudioTracks(self) -> list[MediaStreamTrack]:
        ...
    def getTrackById(self, id: str) -> MediaStreamTrack | None:
        ...
    def getTracks(self) -> list[MediaStreamTrack]:
        ...
    def getVideoTracks(self) -> list[MediaStreamTrack]:
        ...
    def removeTrack(self, track: MediaStreamTrack) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def id(self) -> str:
        ...
class RTCIceTransport:
    _listeners: typing.Any
    def __init__(self) -> None:
        ...
    def _surfaceCandidate(self) -> None:
        ...
    def _surfaceGatheringState(self, state: webrtc.enums.CricketIceGatheringState) -> None:
        ...
    def _surfaceState(self, state: webrtc.enums.RTCIceTransportState) -> None:
        ...
    def addRemoteCandidate(self, candidate: str, sdpMid: str, sdpMLineIndex: typing.SupportsInt | typing.SupportsIndex, usernameFragment: str | None) -> None:
        ...
    def gather(self, policy: webrtc.enums.RTCIceTransportPolicy, iceServers: collections.abc.Sequence[IceServerInit]) -> None:
        ...
    def getLocalCandidates(self) -> list[IceCandidateInit]:
        ...
    def getLocalParameters(self) -> tuple[str, str] | None:
        ...
    def getRemoteCandidates(self) -> list[IceCandidateInit]:
        ...
    def getRemoteParameters(self) -> tuple[str, str] | None:
        ...
    def getSelectedCandidatePair(self) -> tuple[IceCandidateInit, IceCandidateInit, bool] | None:
        ...
    def start(self, usernameFragment: str, password: str, role: webrtc.enums.RTCIceRole) -> None:
        ...
    def stop(self) -> None:
        ...
    @property
    def _standalone(self) -> bool:
        ...
    @property
    def component(self) -> webrtc.enums.RTCIceComponent:
        ...
    @property
    def gatheringState(self) -> webrtc.enums.CricketIceGatheringState:
        ...
    @property
    def role(self) -> webrtc.enums.RTCIceRole:
        ...
    @property
    def state(self) -> webrtc.enums.RTCIceTransportState:
        ...
class RTCDtlsTransport:
    _listeners: typing.Any
    def _surfaceState(self, state: webrtc.enums.DtlsTransportState) -> None:
        ...
    def getRemoteCertificates(self) -> list:
        ...
    @property
    def iceTransport(self) -> RTCIceTransport:
        ...
    @property
    def state(self) -> webrtc.enums.DtlsTransportState:
        ...
class RTCSctpTransport:
    _listeners: typing.Any
    def _surfaceState(self, state: webrtc.enums.SctpTransportState) -> None:
        ...
    @property
    def maxChannels(self) -> int | None:
        ...
    @property
    def maxMessageSize(self) -> float | None:
        ...
    @property
    def state(self) -> webrtc.enums.SctpTransportState:
        ...
    @property
    def transport(self) -> RTCDtlsTransport:
        ...
class RTCDTMFSender:
    _listeners: typing.Any
    def _surfaceBuffer(self, buffer: str, insertion: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def insertDTMF(self, tones: str, duration: typing.SupportsInt | typing.SupportsIndex, interToneGap: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def canInsertDTMF(self) -> bool:
        ...
    @property
    def toneBuffer(self) -> str:
        ...
class RTCRtpSender:
    @staticmethod
    def getCapabilities(kind: str) -> RtpCapabilities | None:
        ...
    def _expireParameters(self, transactionId: str | None = None) -> None:
        ...
    def _lastParameters(self) -> RtpParameters | None:
        ...
    def _transceiverStopped(self) -> bool:
        ...
    def getParameters(self) -> RtpParameters:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    def getStreamIds(self) -> list[str]:
        ...
    def replaceTrack(self, track: MediaStreamTrack | None) -> bool:
        ...
    def setParameters(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], parameters: RtpParameters) -> None:
        ...
    def setStreams(self, streamIds: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def dtmf(self) -> RTCDTMFSender:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def track(self) -> MediaStreamTrack | None:
        ...
    @property
    def transport(self) -> RTCDtlsTransport | None:
        ...
class RTCRtpReceiver:
    @staticmethod
    def getCapabilities(kind: str) -> RtpCapabilities | None:
        ...
    def _getSources(self) -> list[tuple[bool, int, float, int, int | None]]:
        ...
    def getParameters(self) -> RtpParameters:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    @property
    def jitterBufferTarget(self) -> float | None:
        ...
    @jitterBufferTarget.setter
    def jitterBufferTarget(self, arg1: typing.SupportsFloat | typing.SupportsIndex | None) -> None:
        ...
    @property
    def track(self) -> MediaStreamTrack:
        ...
    @property
    def transport(self) -> RTCDtlsTransport | None:
        ...
class RTCRtpTransceiver:
    direction: webrtc.enums.TransceiverDirection
    def getCodecPreferences(self) -> list[RtpCodecCapability]:
        ...
    def getHeaderExtensionsToNegotiate(self) -> list[RtpHeaderExtensionCapability]:
        ...
    def getNegotiatedHeaderExtensions(self) -> list[RtpHeaderExtensionCapability]:
        ...
    def setCodecPreferences(self, codecs: collections.abc.Sequence[RtpCodecCapability]) -> None:
        ...
    def setHeaderExtensionsToNegotiate(self, extensions: collections.abc.Sequence[RtpHeaderExtensionCapability]) -> None:
        ...
    def stop(self) -> None:
        ...
    @property
    def currentDirection(self) -> webrtc.enums.TransceiverDirection | None:
        ...
    @property
    def kind(self) -> webrtc.enums.MediaType:
        ...
    @property
    def mid(self) -> str | None:
        ...
    @property
    def receiver(self) -> RTCRtpReceiver:
        ...
    @property
    def sender(self) -> RTCRtpSender:
        ...
    @property
    def stopped(self) -> bool:
        ...
    @property
    def stopping(self) -> bool:
        ...
class DataChannelMessage:
    @property
    def data(self) -> typing.Any:
        ...
class RTCDataChannel:
    _listeners: typing.Any
    binaryType: str
    def _decreaseBufferedAmount(self, sent: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def _release(self) -> None:
        ...
    def _surfaceState(self, state: webrtc.enums.RTCDataChannelState) -> None:
        ...
    def close(self) -> None:
        ...
    def send(self, data: str, binary: bool) -> None:
        ...
    @property
    def bufferedAmount(self) -> int:
        ...
    @property
    def bufferedAmountLowThreshold(self) -> int:
        ...
    @bufferedAmountLowThreshold.setter
    def bufferedAmountLowThreshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def id(self) -> int | None:
        ...
    @property
    def label(self) -> str:
        ...
    @property
    def maxPacketLifeTime(self) -> int | None:
        ...
    @property
    def maxRetransmits(self) -> int | None:
        ...
    @property
    def negotiated(self) -> bool:
        ...
    @property
    def ordered(self) -> bool:
        ...
    @property
    def priority(self) -> webrtc.enums.RTCPriorityType:
        ...
    @property
    def protocol(self) -> str:
        ...
    @property
    def readyState(self) -> webrtc.enums.RTCDataChannelState:
        ...
class RTCPeerConnection:
    _listeners: typing.Any
    @staticmethod
    def _connectionOf(sender: RTCRtpSender) -> RTCPeerConnection | None:
        ...
    def __init__(self, arg0: ConfigurationInit | None) -> None:
        ...
    def _applyDescriptions(self, snapshot: typing.SupportsInt | typing.SupportsIndex | None = None) -> None:
        ...
    def _refreshDescriptions(self) -> None:
        ...
    def _shouldFireNegotiationNeededEvent(self, eventId: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def _surfaceConnectionState(self, state: webrtc.enums.RTCPeerConnectionState) -> None:
        ...
    def _surfaceIceConnectionState(self, state: webrtc.enums.RTCIceConnectionState) -> None:
        ...
    def _surfaceIceGatheringState(self, state: webrtc.enums.RTCIceGatheringState) -> None:
        ...
    def _surfaceSignalingState(self, state: webrtc.enums.RTCSignalingState) -> None:
        ...
    def addIceCandidate(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], candidate: str, sdpMid: str | None, sdpMLineIndex: typing.SupportsInt | typing.SupportsIndex | None, usernameFragment: str | None) -> None:
        ...
    @typing.overload
    def addTrack(self, track: MediaStreamTrack, stream: MediaStream | None) -> RTCRtpSender:
        ...
    @typing.overload
    def addTrack(self, track: MediaStreamTrack, streams: collections.abc.Sequence[MediaStream]) -> RTCRtpSender:
        ...
    @typing.overload
    def addTransceiver(self, kind: webrtc.enums.MediaType, init: RtpTransceiverInit | None) -> RTCRtpTransceiver:
        ...
    @typing.overload
    def addTransceiver(self, track: MediaStreamTrack, init: RtpTransceiverInit | None) -> RTCRtpTransceiver:
        ...
    def close(self) -> None:
        ...
    def createAnswer(self, onSuccess: collections.abc.Callable[[RTCSessionDescription], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], voiceActivityDetection: bool) -> None:
        ...
    def createDataChannel(self, label: str, ordered: bool, maxPacketLifeTime: typing.SupportsInt | typing.SupportsIndex | None, maxRetransmits: typing.SupportsInt | typing.SupportsIndex | None, protocol: str, negotiated: bool, id: typing.SupportsInt | typing.SupportsIndex | None, priority: webrtc.enums.RTCPriorityType) -> RTCDataChannel:
        ...
    def createOffer(self, onSuccess: collections.abc.Callable[[RTCSessionDescription], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], iceRestart: bool, voiceActivityDetection: bool) -> None:
        ...
    def getConfiguration(self) -> ConfigurationInit:
        ...
    def getReceivers(self) -> list[RTCRtpReceiver]:
        ...
    def getSenders(self) -> list[RTCRtpSender]:
        ...
    def getStats(self, onSuccess: collections.abc.Callable[[str], None], onFailure: collections.abc.Callable[[RTCCallbackException], None]) -> None:
        ...
    def getTransceivers(self) -> list[RTCRtpTransceiver]:
        ...
    def removeTrack(self, sender: RTCRtpSender) -> None:
        ...
    def restartIce(self) -> None:
        ...
    def setConfiguration(self, configuration: ConfigurationInit) -> None:
        ...
    def setLocalDescription(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], description: RTCSessionDescriptionInit | None) -> None:
        ...
    def setRemoteDescription(self, onSuccess: collections.abc.Callable[[], None], onFailure: collections.abc.Callable[[RTCCallbackException], None], description: RTCSessionDescriptionInit) -> None:
        ...
    @property
    def canTrickleIceCandidates(self) -> bool | None:
        ...
    @property
    def connectionState(self) -> webrtc.enums.RTCPeerConnectionState:
        ...
    @property
    def currentLocalDescription(self) -> RTCSessionDescription:
        ...
    @property
    def currentRemoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def iceConnectionState(self) -> webrtc.enums.RTCIceConnectionState:
        ...
    @property
    def iceGatheringState(self) -> webrtc.enums.RTCIceGatheringState:
        ...
    @property
    def localDescription(self) -> RTCSessionDescription:
        ...
    @property
    def pendingLocalDescription(self) -> RTCSessionDescription:
        ...
    @property
    def pendingRemoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def remoteDescription(self) -> RTCSessionDescription:
        ...
    @property
    def sctp(self) -> RTCSctpTransport | None:
        ...
    @property
    def signalingState(self) -> webrtc.enums.RTCSignalingState:
        ...
class VideoFrameBuffer:
    @staticmethod
    def fromData(format: str, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, data: collections.abc.Buffer, layout: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]) -> VideoFrameBuffer:
        ...
    def convertTo(self, destination: collections.abc.Buffer, format: str, x: typing.SupportsInt | typing.SupportsIndex, y: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, offset: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex, matrix: str, fullRange: bool) -> None:
        ...
    def copyPlanes(self, destination: collections.abc.Buffer, planes: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
    def withoutAlpha(self) -> VideoFrameBuffer:
        ...
    @property
    def format(self) -> str:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class MediaStreamTrackProcessor:
    _listeners: typing.Any
    def __init__(self, track: MediaStreamTrack, maxBufferSize: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def _ackWakeup(self) -> None:
        ...
    def cancel(self) -> None:
        ...
    def read(self) -> typing.Any:
        ...
    @property
    def discardedFrames(self) -> int:
        ...
    @property
    def ended(self) -> bool:
        ...
    @property
    def totalFrames(self) -> int:
        ...
class TrackGenerator:
    muted: bool
    def __init__(self, kind: str) -> None:
        ...
    def close(self) -> None:
        ...
    def writeAudio(self, samples: bytes, sampleRate: typing.SupportsInt | typing.SupportsIndex, channels: typing.SupportsInt | typing.SupportsIndex, frames: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def writeVideo(self, buffer: VideoFrameBuffer, timestampUs: typing.SupportsInt | typing.SupportsIndex, rotation: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def kind(self) -> str:
        ...
    @property
    def live(self) -> bool:
        ...
    @property
    def track(self) -> MediaStreamTrack:
        ...
def _alive_factories() -> int:
    ...
def copyAudioSamples(source: collections.abc.Buffer, sourceFormat: str, channels: typing.SupportsInt | typing.SupportsIndex, frames: typing.SupportsInt | typing.SupportsIndex, destination: collections.abc.Buffer, destinationFormat: str, planeIndex: typing.SupportsInt | typing.SupportsIndex, frameOffset: typing.SupportsInt | typing.SupportsIndex, frameCount: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def getUserMedia(audio: bool, video: bool, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, frameRate: typing.SupportsFloat | typing.SupportsIndex) -> MediaStream:
    ...
def ping() -> None:
    ...
