from __future__ import annotations
import typing
from wrtc import Mailbox
class GuardedTask:
    def __call__(self) -> None:
        ...
    @property
    def ran(self) -> int:
        ...
class Counted:
    def __init__(self) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    def guarded(self) -> GuardedTask:
        ...
class Emitting:
    def __init__(self) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    def bind(self, mailbox: Mailbox) -> bool:
        ...
    def inherit(self, parent: Emitting) -> None:
        ...
    def unbind(self) -> None:
        ...
    @property
    def bound(self) -> bool:
        ...
    def emit(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Identity:
    def __init__(self) -> None:
        ...
class Registered:
    @property
    def id(self) -> int:
        ...
    @property
    def createdOnSignalingThread(self) -> bool:
        ...
class Throwing:
    def __init__(self, fail: bool) -> None:
        ...
def abandon(mailbox: Mailbox, token: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def alive_counts() -> dict[str, int]:
    ...
def check_blocking_while_attached() -> None:
    ...
def check_destroyed_off_dispatcher() -> None:
    ...
def complete(mailbox: Mailbox, token: typing.SupportsInt | typing.SupportsIndex, value: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def dispatcher_idle() -> None:
    ...
def dispatcher_threads() -> int:
    ...
def fail(mailbox: Mailbox, token: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def find_registered(identity: Identity) -> Registered | None:
    ...
def park(name: str) -> None:
    ...
def parked(name: str, timeout: typing.SupportsFloat | typing.SupportsIndex) -> bool:
    ...
def post(mailbox: Mailbox, name: str, value: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def post_from_threads(mailbox: Mailbox, threads: typing.SupportsInt | typing.SupportsIndex, count: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def post_unconvertible(mailbox: Mailbox) -> None:
    ...
def registered(identity: Identity) -> Registered:
    ...
def release(name: str) -> None:
    ...
