name: Build

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository.
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python.
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Build.
      run: |
        sudo apt install -y python3.10-dev
        python setup.py build
