name: Build and run tests

on:
  push:
    branches:
      - ci-pytest
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ]

    runs-on: ${{matrix.os}}
    continue-on-error: true

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository.
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python.
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python Dev.
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt install -y python3.9-dev

    - name: Build and install package.
      run: python setup.py install

    - name: Install dev dependencies.
      run: pip install -r requirements-dev.txt

    - name: Run tests.
      run: pytest tests -vv
